<?php

// Cebu cities and municipalities; keep the configuration key for existing callers.
return [
    'Alcantara',
    'Alcoy',
    'Alegria',
    'Aloguinsan',
    'Argao',
    'Asturias',
    'Badian',
    'Balamban',
    'Bantayan',
    'Barili',
    'Bogo City',
    'Boljoon',
    'Borbon',
    'Carcar City',
    'Carmen',
    'Catmon',
    'Cebu City',
    'Compostela',
    'Consolacion',
    'Cordova',
    'Daanbantayan',
    'Dalaguete',
    'Danao City',
    'Dumanjug',
    'Ginatilan',
    'Lapu-Lapu City',
    'Liloan',
    'Madridejos',
    'Malabuyoc',
    'Mandaue City',
    'Medellin',
    'Minglanilla',
    'Moalboal',
    'Naga City',
    'Oslob',
    'Pilar',
    'Pinamungajan',
    'Poro',
    'Ronda',
    'Samboan',
    'San Fernando',
    'San Francisco',
    'San Remigio',
    'Santa Fe',
    'Santander',
    'Sibonga',
    'Sogod',
    'Tabogon',
    'Tabuelan',
    'Talisay City',
    'Toledo City',
    'Tuburan',
    'Tudela',
];
